import type { MusicMix } from '@/types';

export const DEMO_MIXES: MusicMix[] = [
  {
    id: '1',
    style: 'Rap Persa',
    country: 'Irán',
    continent: 'Asia',
    artist: 'Hichkas',
    year: '2000s',
    bpm: 90,
    description: 'El padre del rap persa, mezclando ritmos tradicionales con flujos callejeros de Teherán.',
    searchQuery: 'Hichkas Persian Rap',
    coordinates: { lat: 32.4279, lng: 53.688 },
  },
  {
    id: '2',
    style: 'Rock Progresivo',
    country: 'Italia',
    continent: 'Europa',
    artist: 'Premiata Forneria Marconi',
    year: '1970s',
    bpm: 120,
    description: 'Prog rock italiano que fusiona la música clásica con el rock sinfónico más ambicioso.',
    searchQuery: 'Premiata Forneria Marconi Celebration',
    coordinates: { lat: 41.9029, lng: 12.4534 },
  },
  {
    id: '3',
    style: 'Reggae Eslavo',
    country: 'Polonia',
    continent: 'Europa',
    artist: 'Habakuk',
    year: '1990s',
    bpm: 75,
    description: 'Una visión polaca del roots reggae mezclado con sensibilidades folk eslavas.',
    searchQuery: 'Habakuk Polish Reggae',
    coordinates: { lat: 51.9194, lng: 19.1451 },
  },
  {
    id: '4',
    style: 'Death Metal',
    country: 'Botsuana',
    continent: 'África',
    artist: 'Overthrust',
    year: '2010s',
    bpm: 180,
    description: 'Death metal de la vieja escuela desde la subcultura metalera de Botsuana.',
    searchQuery: 'Overthrust Botswana Metal',
    coordinates: { lat: -22.3285, lng: 24.6849 },
  },
  {
    id: '5',
    style: 'Hip Hop Mongol',
    country: 'Mongolia',
    continent: 'Asia',
    artist: 'Gee',
    year: '2000s',
    bpm: 95,
    description: 'Rap con flujo agresivo en mongol sobre ritmos trap con toques de canto gutural.',
    searchQuery: 'Gee Mongolian Hip Hop',
    coordinates: { lat: 46.8625, lng: 103.8467 },
  },
  {
    id: '6',
    style: 'Cumbia Psicodélica',
    country: 'Perú',
    continent: 'América del Sur',
    artist: 'Los Destellos',
    year: '1970s',
    bpm: 110,
    description: 'Cumbia peruana con guitarras eléctricas surf y efectos psicodélicos amazónicos.',
    searchQuery: 'Los Destellos cumbia psicodelica',
    coordinates: { lat: -12.0464, lng: -77.0428 },
  },
];
